### ISSUE TITLE
FE: Initialize basic CSS/style with Bootstrap

### ISSUE THREAD

**Issue by RainierBastiaans** [Rafdadoumont/UPT-Online-Cafetaria#19]
https://www.bezkoder.com/spring-boot-react-typescript/#Import_Bootstrap_for_React_Typescript_Project

Try this first, look if you're missing something after, such as dependencies/modules/etc. that have to be installed for yourself/locally or maybe even in the project

**Comment by Rafdadoumont** [comment]
Done with Shadcn
